### ISSUE TITLE
how do i setup the metrics action

### ISSUE THREAD

**Issue by neealdon3** [BenjaminHalko/BenjaminHalko#83]

**Comment by BenjaminHalko** [comment]
@neealdon3 I currently use [lowlighter/metrics](github.com/lowlighter/metrics). They have a lot of different customizable metrics.

**Comment by BenjaminHalko** [comment]
I also use [anuraghazra/github-readme-stats](https://github.com/anuraghazra/github-readme-stats) as well.

**Comment by BenjaminHalko** [comment]
As for the GitHub action itself, you would have to give me more details on what you mean by setup...

**Comment by neealdon3** [comment]
nevermind i finnaly fixed it. thanks for the help
